version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn django_sessions.wsgi:application --bind 0.0.0.0:8000
    # automatically restart the container
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    container_name: django_sessions_postgres_prod
    image: postgres
    # automatically restart the container
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    # automatically restart the container
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  db-data:
    name: django_sessions_postgres_prod
  static_volume:
